In [3]:
import numpy as np

In [4]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [5]:
## array indexing
print(arr[0])
print(arr[3])
print(arr[4])

10
40
50


In [6]:
## addation
print(arr + 5)

[15 25 35 45 55]


In [ ]:
### multiplication
print(arr*4)

[ 40  80 120 160 200]
